runtime: java17

instance_class: F1

entrypoint: java -Xmx64m -noverify -jar sistema-academico-0.0.1-SNAPSHOT.jar -cp BOOT-INF/classes/:BOOT-INF/lib/* com.ic045.sistemaacademico.SistemaAcademicoApplication

# See https://cloud.google.com/appengine/docs/standard/serving-static-files?tab=java.
# See https://www.googlecloudcommunity.com/gc/Serverless/Serving-springboot-app-static-resources-from-AppEngine/m-p/178426.
handlers:
  - url: /(.*\.(gif|png|jpg|svg|ico|css|js|html))$
    static_files: BOOT-INF/classes/static/\1
    upload: BOOT-INF/classes/static/.*\.(gif|png|jpg|svg|ico|css|js|html)$
    secure: always
    redirect_http_response_code: 301
    require_matching_file: true
    login: optional
    script: auto
