# Veja https://docs.github.com/en/actions.
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Configura o JDK 17 x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      - name: Verifica as ferramentas necessárias
        run: |
          mvn --version
          npm --version
          yarn --version

      # Veja https://github.com/actions/checkout.
      - name: Faz o checkout do backend
        uses: actions/checkout@v4
        with:
          path: backend

      - name: Faz o checkout do frontend
        uses: actions/checkout@v4
        with:
          repository: ic045-sistemaacademico-2023/frontend-sistema-academico-ic-ufba
          path: frontend

      - name: Compila os arquivos do projeto frontend
        run: |
          cd ${GITHUB_WORKSPACE}/frontend
          yarn
          cp -r \
            ./node_modules \
            ./public \
            ./src \
            ${GITHUB_WORKSPACE}/backend/src/main/resources
          cp \
            ./index.html \
            ./*.js \
            ${GITHUB_WORKSPACE}/backend/src/main/resources

      - name: Cria o pacote do projeto backend
        run: |
          cd ${GITHUB_WORKSPACE}/backend
          rm ${GITHUB_WORKSPACE}/backend/src/main/resources/application.properties
          mvn --batch-mode --update-snapshots package

      - name: Salva o pacote do projeto backend
        run: |
          cp \
            ${GITHUB_WORKSPACE}/backend/target/sistema-academico-0.0.1-SNAPSHOT.jar \
            ${GITHUB_WORKSPACE}/backend/.gcloud
      - uses: actions/upload-artifact@v3
        with:
          name: sistema-academico-0.0.1-SNAPSHOT.jar
          path: .gcloud/sistema-academico-0.0.1-SNAPSHOT.jar

      - id: auth
        name: Autentica na GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: deploy
        name: Instala a aplicação na GCP
        uses: google-github-actions/deploy-appengine@v1
        with:
          working_directory: backend/.gcloud
